var items = [
    {
        id: 1,
        title: "Tha Mi Sgith",
        composer: "Christian Price",
        arranger: "",
        date: new Date(2021, 9, 1),
        genre: "Concert Band/Wind Symphony",
        description: "Tha Mi Sgith, scottish for 'I Am Tired', is a traditional scottish tune about two fairies falling in love. This wind ensemble piece encaptures the tale of the two fairies with a bit of spice to the original scottish folk tune. This piece was commissioned for a community wind ensemble in New York.",
        price: "$99.99",
        difficulty: "3",
        img: "/assets/img/concert/ThaMiSkith.png",
        link: "https://www.youtube.com/embed/YLzCh4a5WzY"
    },
    {
        id: 2,
        title: "Today's Nightmares of Tomorrow's Dreams",
        composer: "Christian Price",
        arranger: "",
        date: new Date(2020, 0, 29),
        genre: "Concert Band/Wind Symphony",
        description: "This piece was made to highlight the imagination one could have while dreaming. Inspired by the events of Coraline, the audience is taken through a land of amazement and terror as things begin to unfold.",
        price: "$79.99",
        difficulty: "3.5",
        img: "/assets/img/concert/today.png",
        link: "https://www.youtube.com/embed/mpmJax-nyUo"
    },
    {
        id: 3,
        title: "99 Red Balloons",
        composer: "Nena",
        arranger: "Christian Price",
        date: new Date(2021, 11, 1),
        genre: "Stand Tunes/Parade",
        description: "99 Red Balloons by Nena arranged for marching band by Christian Price.",
        difficulty: "2",
        img: "/assets/img/standtune.png",
        link: "https://www.youtube.com/embed/YNSsrm0mi6U"
    },
    {
        id: 4,
        title: "Dj Got Us Fallin' in Love",
        composer: "Usher",
        arranger: "Logan Terry",
        date: new Date(2021, 10, 29),
        genre: "Stand Tunes/Parade",
        description: "Dj Got Us Fallin' in Love arranged by Logan Terry for marching band.",
        difficulty: "4",
        img: "/assets/img/standtune.png",
        link: "https://www.youtube.com/embed/pGlHOX-ztNY"
    },
    {
        id: 5,
        title: "Birdland",
        composer: "Joe Zawinul",
        arranger: "Christian Price",
        date: new Date(2021, 10, 18),
        genre: "Stand Tunes/Parade",
        description: "Birdland arranged by Christian Price for marching band.",
        difficulty: "3.5",
        img: "/assets/img/standtune.png",
        link: "https://www.youtube.com/embed/ip9eMECxxXc"
    },
    {
        id: 6,
        title: "I Don't Need Your Rockin' Chair",
        composer: "George Jones",
        arranger: "Christian Price",
        date: new Date(2021, 10, 14),
        genre: "Stand Tunes/Parade",
        description: "I Don't Need Your Rockin' Chair by George Jones arranged by Christian Price for marching band.",
        difficulty: "3.5",
        img: "/assets/img/standtune.png",
        link: "https://www.youtube.com/embed/PXv5KNmVW-s"
    },
    {
        id: 7,
        title: "Down Under",
        composer: "Men at Work",
        arranger: "Christian Price",
        date: new Date(2021, 10, 11),
        genre: "Stand Tunes/Parade",
        description: "Down Under by Men at Work arranged by Christian Price for marching band.",
        difficulty: "3",
        img: "/assets/img/standtune.png",
        link: "https://www.youtube.com/embed/oM9vqEKASQc"
    },
    {
        id: 8,
        title: "Blinding Lights",
        composer: "The Weeknd",
        arranger: "Christian Price",
        date: new Date(2021, 10, 10),
        genre: "Stand Tunes/Parade",
        description: "Arrangement of The Weeknd's Blinding Lights.",
        difficulty: "2.5",
        img: "/assets/img/standtune.png",
        link: "https://www.youtube.com/embed/Cn3aMENOOOk"
    },
    {
        id: 9,
        title: "Pigstep",
        composer: "Lena Raine",
        arranger: "Christian Price",
        date: new Date(2021, 10, 8),
        genre: "Stand Tunes/Parade",
        description: "Pigstep marching band arrangement.",
        difficulty: "2",
        img: "/assets/img/standtune.png",
        link: "https://www.youtube.com/embed/wHwZ5d70pds"
    },
    {
        id: 10,
        title: "Industry Baby",
        composer: "Lil' Nas X",
        arranger: "Christian Price",
        date: new Date(2021, 7, 16),
        genre: "Stand Tunes/Parade",
        description: "Industry Baby marching band arrangement.",
        difficulty: "4",
        img: "/assets/img/standtune.png",
        link: "https://www.youtube.com/embed/Bmjmgk-FT3E"
    },
    {
        id: 11,
        title: "Mi Queso",
        composer: "Christian Price",
        arranger: "",
        date: new Date(2021, 7, 10),
        genre: "Jazz Big Band",
        description: "This contrafact of Granada Smoothie by Mark Taylor explores my amazement of cheese. I really like cheese.",
        difficulty: "3",
        price: "$59.99",
        img: "/assets/img/jazz/miqueso.png",
        link: "https://www.youtube.com/embed/fNk43RVaCfc"
    },
    {
        id: 12,
        title: "Poker Face",
        composer: "Lady Gaga",
        arranger: "Christian Price",
        date: new Date(2021, 7, 9),
        genre: "Stand Tunes/Parade",
        description: "Poker Face marching band arrangement.",
        difficulty: "3",
        img: "/assets/img/standtune.png",
        link: "https://www.youtube.com/embed/JNwSvEtrw7M"
    },
    {
        id: 13,
        title: "1985",
        composer: "SR-71",
        arranger: "Christian Price",
        date: new Date(2021, 6, 18),
        genre: "Stand Tunes/Parade",
        description: "1985 marching band arrangement.",
        difficulty: "3.5",
        img: "/assets/img/standtune.png",
        link: "https://www.youtube.com/embed/0jT6YgPjnzA"
    },
    {
        id: 14,
        title: "Montero (Call me by Your Name)",
        composer: "Lil' Nas X",
        arranger: "Christian Price",
        date: new Date(2021, 4, 20),
        genre: "Stand Tunes/Parade",
        description: "Montero marching band arrangement.",
        difficulty: "4",
        img: "/assets/img/standtune.png",
        link: "https://www.youtube.com/embed/RKPVUR4JDXk"
    },
    {
        id: 15,
        title: "Sea Above the Clouds",
        composer: "Christian Price",
        arranger: "",
        date: new Date(2021, 1, 21),
        genre: "String Orchestra",
        price: "$59.99",
        description: "I started out as a cellist and have always loved how string pieces would have light floaty melodius sections while having heroic articulate moments in the same tune. This piece is my exploration of these two styles.",
        difficulty: "2",
        img: "/assets/img/strings/seaaboveclouds.png",
        link: "https://www.youtube.com/embed/ZebVNq6kAmY"
    },
    {
        id: 16,
        title: "Blue Fire",
        composer: "Christian Price",
        arranger: "",
        date: new Date(2021, 1, 5),
        genre: "Full Orchestra",
        price: "$199.99",
        description: "Most people say that love is red hot at the start of a relationship and as time goes on it can change in many different ways. This orchestral piece tells the story of a love that's made up of blue fire, hotter than red fire, burning passionately.",
        difficulty: "4",
        img: "/assets/img/strings/bluefire.jpg",
        link: "https://www.youtube.com/embed/-e5Pop4aKWU"
    },
    {
        id: 17,
        title: "Astronomia",
        composer: "Vicetone and Tony Igy",
        arranger: "Christian Price",
        date: new Date(2020, 3, 9),
        genre: "Stand Tunes/Parade",
        description: "Also known as the coffin/casket meme.",
        difficulty: "3.5",
        img: "/assets/img/standtune.png",
        link: "https://www.youtube.com/embed/-e5Pop4aKWU"
    },
    {
        id: 18,
        title: "Come Alive",
        composer: "Benj Pasek and Justin Paul",
        arranger: "Christian Price",
        date: new Date(2020, 1, 8),
        genre: "Stand Tunes/Parade",
        description: "Pep/Marching band arrangement commissioned by Perryville High School.",
        difficulty: "3.5",
        img: "/assets/img/standtune.png",
        link: "https://www.youtube.com/embed/jO6I1jiAO8M"
    },
    {
        id: 19,
        title: "2012",
        composer: "Christian Price",
        arranger: "",
        date: new Date(2019, 11, 2),
        genre: "Field Shows",
        price: "$699.99",
        description: "Based on the Mayan prediction of the end of the world, 2012 brings a show to challenge the students and awe the audience. Much of the show relies on heavy rock-like riffs as well as very dissonant chords.",
        difficulty: "4.5",
        img: "/assets/img/fieldshow/2012.png",
        link: "https://www.youtube.com/embed/QE5zvR-tP-I"
    },
    {
        id: 20,
        title: "The Painter",
        composer: "Christian Price",
        arranger: "",
        date: new Date(2019, 11, 2),
        genre: "Field Shows",
        price: "$699.99",
        description: "Listen as the band describes the life of a painter, from his first creations, artistic inspirations, downfall, and his final work of art.",
        difficulty: "3.5",
        img: "/assets/img/fieldshow/painter.png",
        link: "https://www.youtube.com/embed/OylPXh3fFGY"
    },
    {
        id: 21,
        title: "Cool Beans",
        composer: "Christian Price",
        arranger: "",
        date: new Date(2019, 6, 7),
        genre: "Jazz Combo",
        price: "$39.99",
        description: "Jazz combo piece written for Alto Sax. Get ready for some strange harmony.",
        difficulty: "4",
        img: "/assets/img/jazz/coolbeans.png",
        link: "https://www.youtube.com/embed/iEfMBZ7sKuI"
    },
    {
        id: 22,
        title: "West",
        composer: "Christian Price",
        arranger: "",
        date: new Date(2019, 4, 3),
        genre: "String Orchestra",
        price: "$39.99",
        description: "A piece about the struggles and hardships of moving west.",
        difficulty: "4",
        img: "/assets/img/strings/west.png",
        link: "https://www.youtube.com/embed/Qsh2KjThrks"
    },
    {
        id: 23,
        title: "Old Town Road",
        composer: "Lil' Nas X",
        arranger: "Christian Price",
        date: new Date(2019, 3, 8),
        genre: "Stand Tunes/Parade",
        description: "Who can't love this tune that got Lil' Nas X to where he is today?",
        difficulty: "3",
        img: "/assets/img/standtune.png",
        link: "https://www.youtube.com/embed/PWi2aof7AdM"
    },
    {
        id: 24,
        title: "The Iron Curtain",
        composer: "Christian Price",
        arranger: "",
        date: new Date(2019, 3, 6),
        genre: "Concert Band/Wind Symphony",
        description: "This piece was made in rememberance of the Berlin Wall and the difficulties that arose for many people because of it. One can hear the wall being built as well as the effects of war while listening.",
        difficulty: "4",
        price: "$99.99",
        img: "/assets/img/concert/ironcurtain.png",
        link: "https://www.youtube.com/embed/PWi2aof7AdM"
    },
    {
        id: 25,
        title: "Quizzacious",
        composer: "Christian Price",
        arranger: "",
        date: new Date(2018, 11, 5),
        genre: "Jazz Lead Sheets",
        description: "Dumb little jazz solo I wrote.",
        difficulty: "4",
        price: "$19.99",
        img: "/assets/img/jazz/quizzacious.png",
        link: "https://www.youtube.com/embed/EF_v1WGJXWU"
    }
]